version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'dmitriy'
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_DB: 'todomax'
  backend:
    build: ./todomax
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate &&
      python manage.py create_users 2 &&
      gunicorn todomax.wsgi -b 0.0.0.0:8080"
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx

